#pragma once
using namespace std;

#include <generator/generator.hpp>

/**
 * @brief Function that generates a vector with different values that it was generated by one Generator 
 * 
 * @param n Number of elements of the new vector
 * @param g Generator
 * @return vector<int> 
 */
vector<int> generateArray(unsigned int n, Generator& g);

/**
 * @brief Program that generates a new test 
 * 
 * @param name Name of the new test
 * @param n Number of elements of the new vector
 * @param g Generator
 */
void generateTest(const string name, unsigned int n, Generator& g);